#!/usr/bin/perl
if (defined $ARGV[0]) {
	$prefix = $ARGV[0];
} else {
	$prefix = "/usr";
}

print "Copying gnomersvp.plx to " . $prefix . "/bin/........ ";
system("install -D ./gnomersvp.plx $prefix/bin/gnomersvp.plx");
print "[DONE]\n";
print "Adding desktop entry...................... ";
system("install -D ./gnomersvp.desktop $prefix/share/gnome/apps/Applications/gnomersvp.desktop");
print "[DONE]\n";
print "\nInstallation Successful! Type gnomersvp.plx to run!\n";
